### ISSUE TITLE
Use as service

### ISSUE THREAD

**Issue by njrfhtd** [dflourusso/v-file-upload#3]
Thank you for your work.
I want to use it as a service. [https://github.com/dflourusso/v-file-upload#as-service-1](https://github.com/dflourusso/v-file-upload#as-service-1)

`let fileUpload = new FileUploadService`

causes an error:

`TypeError: __WEBPACK_IMPORTED_MODULE_1_v_file_upload __. FileUploadService is not a constructor`

vue version 2.5.3
What am I doing wrong?

**Comment by dflourusso** [comment]
It should be ‘FileUploadService’ instead of ‘FileOploadService’ 😃

**Comment by njrfhtd** [comment]
Sorry, typo
The code is correct, but the error is

**Comment by dflourusso** [comment]
I will check

**Comment by dflourusso** [comment]
I really was an issue.

Update to version 3.1.2

`yarn add v-file-upload@3.1.2`

**Comment by njrfhtd** [comment]
Great
Is the upload cancellation method planned?

Thanks for the work!

**Comment by dflourusso** [comment]
I will implement cancellation ASAP.

**Comment by dflourusso** [comment]
@njrfhtd See: https://github.com/dflourusso/v-file-upload/issues/4
